name: receipt-processor-services
services:
  receipt-processor:
    container_name: receipt-processor
    depends_on:
      postgres:
        condition: service_healthy
    build:
      dockerfile: Dockerfile
      context: .
      args:
        JAR_FILE: "./build/libs/receiptprocessor-1.0.0.jar"
    ports:
      - '8080:8080'
    networks:
      - processor-postgres-network

  postgres:
    container_name: postgres
    hostname: postgres
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=receipt'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=username'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U username" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - processor-postgres-network
networks:
  processor-postgres-network:
